import Foundation

/// A type that can read/write a value from a firestore
///
/// This type provides the identification values required for the data types used to access Firestore and Shared.
///
/// ```swift
/// private struct Todo: Sendable, Codable, DocumentIdentifiable {
///   var clientId: UUID = .init()
///   @DocumentID var documentId: String?
///   var memo: String
///   var completed: Bool
///   var createdAt: Date = .init()
/// }
/// ```
public protocol DocumentIdentifiable: Identifiable {
  /// The `documentId` is generated by Firestore after the document is saved.
  /// While creating a new document locally, `documentId` is `nil`.
  /// In SwiftUI, using List or ForEach may cause undefined behavior
  /// if the `id` is unknown or unstable during view updates.
  /// In such cases, `clientId` is used as a fallback to provide a stable identity.
  var clientId: UUID { get }
  
  var documentId: String? { get }
}

extension DocumentIdentifiable {
  public var id: UUID { clientId }
}
